In [66]:
import pandas as pd
import matplotlib.pyplot as plt
from pandas.tools.plotting import lag_plot
from pandas.tools.plotting import autocorrelation_plot
import seaborn as sns
import os
% matplotlib inline

In [75]:
files = os.listdir("climate_data")

climate_files = []
for file in files:
    if "Annual" in file and ".txt" in file:
        climate_files.append(file)

processed_file_names = []
for file_name in climate_files:
    new_file_name = file_name[:-4] + " clean.csv"
    #print(new_file_name)
    new_file = open(new_file_name, 'w+')
    file = open("climate_data/" + file_name, "r")
    header = "{0},{1}\n".format("Year", file_name[:-14])
    new_file.writelines(header)
    for line in file:
        year = int(line[:4])
        
        if year < 1990 or year > 2014:
            continue
            
        data = ""
        for char in line[12:]:
            if char == " ":
                continue
            else:
                data += char
                
        new_line = "{0},{1}\n".format(year, float(data))
        new_file.writelines(new_line)
        
    processed_file_names.append(new_file_name)
    new_file.close()
    file.close()

climate_df = pd.read_csv(processed_file_names[0], encoding="UTF-8")

for i in range(1, len(processed_file_names)):
    file_name = processed_file_names[i]
    temp_climate_df = pd.read_csv(file_name, encoding="UTF-8")
    climate_df = pd.merge(climate_df, temp_climate_df)
climate_df

,Year,Annual 9am Cloud VIC,Annual Daytime Cloud VIC,Annual Diurnal T Rang Anomaly VIC,Annual Maximum Temperature Anomaly VIC,Annual Mean Temperature Anomaly VIC,Annual Minimum Temperature Anomaly VIC,Annual Pan Evaporation VIC
0,1990.0,4.47,4.61,-0.11,0.44,0.50,0.56,1451.83
1,1991.0,4.45,4.54,0.02,0.25,0.24,0.23,1412.76
2,1992.0,4.94,5.06,-1.02,-0.90,-0.38,0.14,1198.91
3,1993.0,4.44,4.62,-0.11,0.09,0.16,0.21,1263.50
4,1994.0,4.33,4.47,0.72,0.36,-0.00,-0.37,1426.07
5,1995.0,4.66,4.79,-0.45,-0.65,-0.41,-0.19,1367.18
6,1996.0,4.53,4.69,-0.28,-0.64,-0.49,-0.35,1369.20
7,1997.0,4.22,4.35,0.73,0.63,0.27,-0.10,1516.27
8,1998.0,4.31,4.45,0.33,0.20,0.05,-0.12,1469.31
9,1999.0,4.21,4.41,0.24,0.58,0.47,0.34,1402.23
10,2000.0,4.35,4.55,0.02,0.56,0.56,0.54,1433.38
11,2001.0,4.49,4.66,0.04,0.52,0.51,0.48,1391.74
12,2002.0,4.11,4.27,0.98,0.93,0.44,-0.05,1554.03
13,2003.0,4.11,4.24,0.19,0.40,0.31,0.21,1498.89
14,2004.0,4.27,4.43,0.38,0.31,0.12,-0.07,1477.80
15,2005.0,4.29,4.38,0.58,0.81,0.52,0.23,1501.53
16,2006.0,3.93,3.96,1.34,1.02,0.36,-0.31,1649.93
17,2007.0,4.11,4.20,0.46,1.42,1.20,0.96,1602.39
18,2008.0,4.38,4.42,0.35,0.56,0.40,0.22,1549.12
19,2009.0,4.31,4.39,0.64,1.37,1.06,0.74,1601.94
20,2010.0,4.74,4.91,-0.34,0.26,0.44,0.61,1348.04
21,2011.0,4.66,4.74,-0.29,0.38,0.53,0.67,1271.33
22,2012.0,4.68,4.82,0.43,0.65,0.44,0.22,1454.39
23,2013.0,4.55,4.68,0.53,1.30,1.04,0.77,1519.50
24,2014.0,4.37,4.49,0.75,1.53,1.15,0.77,1509.34